spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third-route
          uri: lb://third
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/api/third/(?<segment>.*),/$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
